server.port: 8890

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: dev

  boot:
    admin:
      client:
        url: http://localhost:8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

---
spring:
  profiles: kubernetes

  boot:
    admin:
      client:
        url: http://admin-server:8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/
