server.port: 8890

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: dev

boot:
  admin:
    client:
      url: http://localhost:8079

codex:
  security:
    rsaPublicKey: ${CODEX_RSA_PUBLIC_KEY}
    rsaPrivateKey: ${CODEX_RSA_PRIVATE_KEY}
    tokenExpiration: PT1H

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/